name: 'Regression Tests'
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  reg-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Get Python
        uses: actions/setup-python@v4
      - name: Fetch Build Dependencies
        run: sudo apt-get install -y ninja-build clang-tidy clang-format gcovr
      - name: Fetch meson
        run: sudo python3 -m pip install meson

      - name: Fetch Submodules
        run: git submodule update --init --recursive

      - name: Setup Build Directory
        run: meson setup build

      - name: Attempt to Build
        working-directory: ./build
        run: meson compile

      - name: Link compile_commands.json
        run: ln -s ./build/compile_commands.json compile_commands.json

      - name: Attempt to Autolint
        working-directory: ./build
        run: meson compile auto-lint

      - name: Push Lint
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'Auto-Lint Bot'

      - name: Lint
        working-directory: ./build
        run: meson compile lint

      - name: Test
        working-directory: ./build
        run: meson test

      - name: Calculate Coverage
        working-directory: ./build
        run: ninja coverage-text && cat meson-logs/coverage.txt
